language: php

php:
  - 5.5
  - 5.6

before_script:
  - composer install
#  - wget http://getcomposer.org/composer.phar
#  - php composer.phar require satooshi/php-coveralls:dev-master --dev --no-progress --prefer-source

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls --exclude-no-stmt

after_success:
  - coveralls
